name: CI/CD - Node.js

on:
  push:
    branches: [ main ] 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Cloner le dépôt
      uses: actions/checkout@v3

    - name: 🧰 Installer Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22' 

    - name: 📦 Installer les dépendances
      run: npm install

    - name: 🚀 Déploiement (placeholder)
      run: echo "Déploiement ici"
